### ISSUE TITLE
Unable to print German character in FPDF

### ISSUE THREAD

**Issue by teamjhuns2014** [ravage84/SwissPaymentSlipPdf#7]
Hi There, 

I am trying to generate Payment Slip from Vtiger and using this module. But somehow the german characters r not getting displayed in payment slip. Can nyone guide please.

AJ

**Comment by teamjhuns2014** [comment]
Thanks for revert.. whats your skype ID ? 

AJ

**Comment by ravage84** [comment]
The problem was wrong (HTML special chars) encoding of the data displayed.
