### ISSUE TITLE
Make this the main SwissPaymentSlip Library utilizing Composer virtual packages

### ISSUE THREAD

**Issue by ravage84** [ravage84/SwissPaymentSlipPdf#8]
To simplify the usage of the library or better said the whole [SwissPaymentSlip library family](https://packagist.org/search/?q=swiss-payment-slip), we could make this the main package and convert the [TCPDF](https://github.com/ravage84/SwissPaymentSliptcpdf) and [FPDF](https://github.com/ravage84/SwissPaymentSlipfpdf) implementation into interface providing packages.

This package would depend on an virtual package, e.g. ``swiss-payment-slip/swiss-payment-slip-pdf-implementation``, while the two specific implementation would [provide](https://getcomposer.org/doc/04-schema.md#provide) such aninterface.

Inspiration taken from:
http://docs.php-http.org/en/latest/clients.html#composer-virtual-packages

**Comment by sdespont** [comment]
Hi @ravage84,

[FPDF](http://www.fpdf.org/) is not maintained for **more than 2 years now** (last update 2015-12-20). I would suggest to drop the support instead of create virtual package or other developement efforts.

Best regards,

Sébastien

**Comment by ravage84** [comment]
I'm not going to implement or action this, anymore, as this package has become obsolete due to the introduction of the [Swiss QR code payment slip](https://de.wikipedia.org/wiki/QR-Rechnung) and the discontinuation of the old ESR.

One can use https://github.com/sprain/php-swiss-qr-bill for the new Swiss QR  bill.
